### ISSUE TITLE
生成的视频盖了一层红绿蓝的栅格是什么原因,调整比特率也不行,argb转yuv的算法有没有可能有问题呢?

### ISSUE THREAD

**Issue by Paladindin** [xiaoyifan6/videocreator#3]

**Comment by ShuoHuang** [comment]
我生成的视频也有这个现象，解决了吗？

**Comment by Paladindin** [comment]
> 我生成的视频也有这个现象，解决了吗？

我的问题就出在argb转yuv那里,获取支持的解码列表时,只有yuv420sp,yuv420p这两种数据格式是好的,其他数据格式的会有栅格,这里写死两种就解决了

**Comment by ShuoHuang** [comment]
> > 我生成的视频也有这个现象，解决了吗？
> 
> 我的问题就出在argb转yuv那里,获取支持的解码列表时,只有yuv420sp,yuv420p这两种数据格式是好的,其他数据格式的会有栅格,这里写死两种就解决了

谢谢
